# set escape time to 0ms
set -s escape-time 0

# start new window or pane in current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
