# Set $TERM to 'tmux-256color' (default was 'screen') (fixes italic rendering)
set -g default-terminal "tmux-256color"

# Set status bar background to white
set -g status-bg white

# Set escape time to 0ms
set -s escape-time 0

# Start new window or pane in current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Copy selection to clipboard
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
